version: '3'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  # Database Service
  db:
    image : mysql
    container_name : mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password

  # Application Service
  app:
    container_name: sample-app
    build: 
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
